version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./db_backup:/data_con
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        # ports:
        # - 27017:27017
        environment:
            MONGO_DB: delta-green
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: Ny4rl47073P
        networks:
            - database

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: Ny4rl47073P
        networks:
            - database
            
    delta-green:
        image: 'node:12'
        restart: always
        user: 'node'
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
            - HAPI_PORT=4728
            - MONGO_DB_DATABASE=delta-green
        volumes:
            - ./:/home/node/app
        links:
            - mongo
        ports:
            - '33582:33582'
            - '9229:9229'
        command: 'yarn docker:debug'
        networks:
            - database

networks:
    database:
